spring:
  application:
    name: spring boot
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
server:
  port: 5000
jwt:
  token:
    header: Authorization
    issuer:
    client-secret:
    expiry-seconds: 600
